"use strict";
const REFRESH_INTERVAL_MS = 1000;
const MIDAS_SUCCESS = 1;
const ODB = Object.freeze({
  globalSeverity:"/DAQ/Status/Global/Severity",globalSummary:"/DAQ/Status/Global/Summary",canStart:"/DAQ/Status/Global/CanStart",canStartReason:"/DAQ/Status/Global/CanStartReason",runNumber:"/DAQ/Status/Run/RunNumber",runState:"/DAQ/Status/Run/State",runDuration:"/DAQ/Status/Run/DurationSec",
  vmeSeverity:"/DAQ/Status/Frontends/VME/Severity",vmeReason:"/DAQ/Status/Frontends/VME/Reason",vmeConnected:"/DAQ/Status/Frontends/VME/Connected",vmeEventSlip:"/DAQ/Status/Frontends/VME/EventSlipCount",v1720CounterDiscontinuity:"/DAQ/Status/Frontends/VME/CounterDiscontinuityCount",
  easirocSeverity:"/DAQ/Status/Frontends/EASIROC/Severity",easirocReason:"/DAQ/Status/Frontends/EASIROC/Reason",easirocConnected:"/DAQ/Status/Frontends/EASIROC/Connected",loggerSeverity:"/DAQ/Status/Logger/Severity",loggerConnected:"/DAQ/Status/Logger/Connected",currentFilename:"/DAQ/Status/Logger/CurrentFilename",diskSeverity:"/DAQ/Status/Disk/Severity",diskPath:"/DAQ/Status/Disk/Path",diskFree:"/DAQ/Status/Disk/FreeGB",diskTotal:"/DAQ/Status/Disk/TotalGB",
  vmeEventRate:"/Equipment/VME/Statistics/Events per sec.",vmeDataRate:"/Equipment/VME/Statistics/kBytes per sec.",vmeEventCount:"/Equipment/VME/Statistics/Events sent",easirocEventRate:"/Equipment/NIM-EASIROC Physics/Statistics/Events per sec.",easirocDataRate:"/Equipment/NIM-EASIROC Physics/Statistics/kBytes per sec.",easirocEventCount:"/Equipment/NIM-EASIROC Physics/Statistics/Events sent",
  v792Address:"/Equipment/VME/Info/V792/BaseAddress",v792Enabled:"/Equipment/VME/Variables/V792/EnabledForRun",v792Communication:"/Equipment/VME/Variables/V792/CommunicationOK",
  v1190Address:"/Equipment/VME/Info/V1190/BaseAddress",v1190Enabled:"/Equipment/VME/Variables/V1190/EnabledForRun",v1190Communication:"/Equipment/VME/Variables/V1190/CommunicationOK",
  v1720eAddress:"/Equipment/VME/Info/V1720E/BaseAddress",v1720eEnabled:"/Equipment/VME/Variables/V1720E/EnabledForRun",v1720eCommunication:"/Equipment/VME/Variables/V1720E/CommunicationOK",
  v775Address:"/Equipment/VME/Info/V775/BaseAddress",v775Enabled:"/Equipment/VME/Variables/V775/EnabledForRun",v775Communication:"/Equipment/VME/Variables/V775/CommunicationOK",
  rpv130Address:"/Equipment/VME/Info/RPV130/BaseAddress",rpv130Enabled:"/Equipment/VME/Variables/RPV130/EnabledForRun",rpv130Communication:"/Equipment/VME/Variables/RPV130/CommunicationOK",
  easirocAddress:"/Equipment/EASIROC/Settings/Network/IPAddress",easirocEnabled:"/Equipment/EASIROC/Variables/EnabledForRun",easirocCommunication:"/Equipment/EASIROC/Variables/RBCPCommunicationOK",easirocTcpReachable:"/Equipment/EASIROC/Variables/TCPReachable",easirocTcpConnected:"/Equipment/EASIROC/Variables/TCPConnected",easirocAcquisitionRunning:"/Equipment/EASIROC/Variables/AcquisitionRunning"
});
const ODB_PATHS=Object.values(ODB);let mockMode=false,transitionPending=false,lastCanStart=false,lastRunState="—";
const element=id=>document.getElementById(id);const valid=v=>v!==null&&v!==undefined&&v!=="";const text=(id,v,f="—")=>{element(id).textContent=valid(v)?String(v):f;};
function severityClass(s){return s==="OK"?"severity-ok":s==="WARNING"?"severity-warning":s==="ERROR"?"severity-error":"severity-unknown";}
function setSeverityBackground(id,s){element(id).className=`status-hero ${severityClass(s)}`;}
function count(v){if(!valid(v))return "—";const n=Number(v);return Number.isFinite(n)?Math.trunc(n).toLocaleString("en-US"):"—";}function rate(v){if(!valid(v))return "—";const n=Number(v);return Number.isFinite(n)?n.toLocaleString("en-US",{maximumFractionDigits:n<10?2:1}):"—";}function dataRate(v){if(!valid(v))return "—";const n=Number(v);return !Number.isFinite(n)?"—":Math.abs(n)>=1000?`${(n/1000).toFixed(2)} MB/s`:`${n.toFixed(1)} kB/s`;}
function duration(v){const n=Number(v);if(!Number.isFinite(n)||n<0)return "—";return[Math.floor(n/3600),Math.floor(n%3600/60),Math.floor(n%60)].map(x=>String(x).padStart(2,"0")).join(":");}function state(v){return Number(v)===1?"STOPPED":Number(v)===2?"PAUSED":Number(v)===3?"RUNNING":"—";}function hex(v){const n=Number(v);return Number.isFinite(n)?`0x${Math.trunc(n).toString(16).toUpperCase().padStart(8,"0")}`:"—";}
function status(id,label,kind){const e=element(id);e.textContent=label;e.className=`component-status state-${kind}`;}
function moduleStatus(prefix,v){const enabled=v(`${prefix}Enabled`);if(enabled===false||enabled===0){status(`${prefix}-status`,`Disabled`,`disabled`);return;}const communication=v(`${prefix}Communication`);status(`${prefix}-status`,communication===true||communication===1?`Comm OK`:`Comm Error`,communication===true||communication===1?`connected`:`severity-error`);}
function countWithRunLabel(v,running){const result=count(v);return result==="—"?result:running?result:`${result} (last run)`;}
function render(values){const v=name=>values[ODB[name]],run=state(v("runState")),running=run==="RUNNING";lastRunState=run;setSeverityBackground("global-status",v("globalSeverity"));text("global-severity",v("globalSeverity"));text("global-summary",v("globalSummary"),"No summary available");text("run-number",v("runNumber"));text("run-state",run);text("run-duration",duration(v("runDuration")));text("run-events-label",running?"Events":"Events (last run)");text("run-events",`VME ${countWithRunLabel(v("vmeEventCount"),running)} · EASIROC ${countWithRunLabel(v("easirocEventCount"),running)}`);text("events-column-note",running?"Count / capacity":"Count / capacity (last run)");
lastCanStart=v("canStart")===true||v("canStart")===1;text("can-start",lastCanStart?"READY":"BLOCKED");text("can-start-reason",v("canStartReason"),lastCanStart?"All pre-start checks passed":"No reason available");updateButtons();
["v792","v1190","v1720e","v775"].forEach(p=>{text(`${p}-address`,hex(v(`${p}Address`)));moduleStatus(p,v);});text("rpv130-address",hex(v("rpv130Address")));moduleStatus("rpv130",v);const frontendState=(connected)=>connected===true||connected===1?"Connected":connected===false||connected===0?"Disconnected":"—";status("vme-frontend-status",frontendState(v("vmeConnected")),v("vmeConnected")?"connected":"disconnected");status("easiroc-frontend-status",frontendState(v("easirocConnected")),v("easirocConnected")?"connected":"disconnected");text("easiroc-address",v("easirocAddress"));moduleStatus("easiroc",v);const rbcpOk=v("easirocCommunication")===true||v("easirocCommunication")===1;const tcpReachable=v("easirocTcpReachable")===true||v("easirocTcpReachable")===1;const tcpConnected=v("easirocTcpConnected")===true||v("easirocTcpConnected")===1;const acquisitionRunning=v("easirocAcquisitionRunning")===true||v("easirocAcquisitionRunning")===1;if(v("easirocEnabled")!==false&&v("easirocEnabled")!==0){const hardwareOk=running?rbcpOk&&tcpReachable&&tcpConnected&&acquisitionRunning:rbcpOk;status("easiroc-status",hardwareOk?"Comm OK":"Comm Error",hardwareOk?"connected":"severity-error");}
status("logger-status",v("loggerConnected")?"Connected":"Disconnected",v("loggerConnected")?"connected":"disconnected");text("disk-address",v("diskPath"));const diskSeverity=v("diskSeverity");status("disk-status",diskSeverity||"—",diskSeverity==="OK"?"severity-ok":diskSeverity==="WARNING"?"severity-warning":diskSeverity==="ERROR"?"severity-error":"unknown");const free=rate(v("diskFree")),total=rate(v("diskTotal"));text("disk-capacity",free==="—"?"—":`${free} / ${total==="—"?"—":total} GB`);
text("vme-event-rate",rate(v("vmeEventRate")));text("vme-data-rate",dataRate(v("vmeDataRate")));text("vme-event-count",countWithRunLabel(v("vmeEventCount"),running));text("easiroc-event-rate",rate(v("easirocEventRate")));text("easiroc-data-rate",dataRate(v("easirocDataRate")));text("easiroc-event-count",countWithRunLabel(v("easirocEventCount"),running));text("current-filename",v("currentFilename"),"No active file");text("disk-path",v("diskPath"));text("disk-free",free);text("error-event-slip",count(v("vmeEventSlip")));text("error-v1720-discontinuity",count(v("v1720CounterDiscontinuity")));text("error-vme-reason",v("vmeReason"));text("error-easiroc-reason",v("easirocReason"));text("error-global-summary",v("globalSummary"));text("last-refresh",`Updated ${new Date().toLocaleTimeString()}`);}
function updateButtons(){element("start-button").disabled=mockMode||transitionPending||!lastCanStart||lastRunState!=="STOPPED";element("stop-button").disabled=mockMode||transitionPending||lastRunState==="STOPPED"||lastRunState==="—";}
function valuesFromRpc(rpc){const values={};ODB_PATHS.forEach((p,i)=>values[p]=rpc.result.status[i]===MIDAS_SUCCESS?rpc.result.data[i]:null);return values;}function showError(m){text("connection-error",m);element("connection-error").hidden=false;}function clearError(){element("connection-error").hidden=true;}
async function refreshDashboard(){try{render(valuesFromRpc(await mjsonrpc_db_get_values(ODB_PATHS)));clearError();}catch(error){showError(`Cannot refresh MIDAS status: ${mjsonrpc_decode_error(error)}`);}finally{window.setTimeout(refreshDashboard,REFRESH_INTERVAL_MS);}}
async function requestTransition(transition){if(mockMode||transitionPending||(transition==="TR_START"&&(!lastCanStart||lastRunState!=="STOPPED"))||(transition==="TR_STOP"&&lastRunState==="STOPPED"))return;transitionPending=true;updateButtons();text("transition-status",transition==="TR_START"?"Starting run…":"Stopping run…");try{const rpc=await mjsonrpc_call("cm_transition",{transition});if(rpc.result.status!==MIDAS_SUCCESS)throw new Error(rpc.result.error_string||`MIDAS transition status ${rpc.result.status}`);text("transition-status",transition==="TR_START"?"Run started":"Run stopped");}catch(error){showError(`Transition failed: ${typeof mjsonrpc_decode_error==="function"?mjsonrpc_decode_error(error):String(error)}`);text("transition-status","Transition failed");}finally{transitionPending=false;updateButtons();}}
function initializeDashboard(){const query=new URLSearchParams(window.location.search);mockMode=query.get("mock")!==null;element("start-button").addEventListener("click",()=>requestTransition("TR_START"));element("stop-button").addEventListener("click",()=>requestTransition("TR_STOP"));if(mockMode){document.body.classList.add("mock-mode");element("mock-notice").hidden=false;render(query.get("mock")==="stopped"?window.DAQ_MOCK_STOPPED_DATA:window.DAQ_MOCK_DATA);return;}mhttpd_init("DAQ",REFRESH_INTERVAL_MS);refreshDashboard();}
