"use strict";
const BASE={
 "/DAQ/Status/Global/Severity":"OK","/DAQ/Status/Global/Summary":"DAQ OK","/DAQ/Status/Global/CanStart":false,"/DAQ/Status/Global/CanStartReason":"Run in progress","/DAQ/Status/Run/RunNumber":42,"/DAQ/Status/Run/State":3,"/DAQ/Status/Run/DurationSec":90,"/Runinfo/Start time":"2026-09-21 08:00:00","/Runinfo/Stop time":"2026-09-21 10:10:23","/Experiment/Run Parameters/Type":"Data","/Experiment/Run Parameters/Comment":"Mock run comment",
 "/DAQ/Status/Frontends/VME/Severity":"OK","/DAQ/Status/Frontends/VME/Reason":"VME OK","/DAQ/Status/Frontends/VME/Connected":true,"/DAQ/Status/Frontends/VME/Participating":true,"/DAQ/Status/Frontends/VME/EventSlipCount":0,"/DAQ/Status/Frontends/EASIROC/Severity":"OK","/DAQ/Status/Frontends/EASIROC/Reason":"EASIROC OK","/DAQ/Status/Frontends/EASIROC/Connected":true,"/DAQ/Status/Frontends/EASIROC/Participating":true,
 "/DAQ/Status/Logger/CurrentFilename":"/home/daq/midas/midas/data/run00042.mid.lz4","/DAQ/Status/Disk/Severity":"OK","/DAQ/Status/Disk/Path":"/home/daq/midas/midas/data","/DAQ/Status/Disk/FreeGB":398.9,"/DAQ/Status/Disk/TotalGB":407.4,
 "/Equipment/VME/Statistics/Events per sec.":1248.2,"/Equipment/VME/Statistics/kBytes per sec.":318.7,"/Equipment/VME/Statistics/Events sent":2415890,"/Equipment/NIM-EASIROC Physics/Statistics/Events per sec.":1247.9,"/Equipment/NIM-EASIROC Physics/Statistics/kBytes per sec.":92.4,"/Equipment/NIM-EASIROC Physics/Statistics/Events sent":2415321,"/DAQ/Status/Runlog/EORCompleteRunNumber":42,"/DAQ/Status/Runlog/VMEEvents":2415891,"/DAQ/Status/Runlog/EASIROCEvents":2415322,
 "/Equipment/VME/Info/V792/BaseAddress":6291456,"/Equipment/VME/Settings/V792/Enabled":true,"/Equipment/VME/Variables/V792/CommunicationOK":true,"/Equipment/VME/Info/V1190/BaseAddress":12648448,"/Equipment/VME/Settings/V1190/Enabled":true,"/Equipment/VME/Variables/V1190/CommunicationOK":true,"/Equipment/VME/Info/V1720E/BaseAddress":286326784,"/Equipment/VME/Settings/V1720E/Enabled":true,"/Equipment/VME/Variables/V1720E/CommunicationOK":true,"/Equipment/VME/Info/V775/BaseAddress":0,"/Equipment/VME/Settings/V775/Enabled":false,"/Equipment/VME/Variables/V775/CommunicationOK":false,"/Equipment/VME/Info/RPV130/BaseAddress":36848,"/Equipment/VME/Settings/RPV130/Enabled":true,"/Equipment/VME/Variables/RPV130/CommunicationOK":true,
 "/Equipment/EASIROC/Settings/Network/IPAddress":"192.168.10.26","/Equipment/EASIROC/Settings/Enabled":true,"/Equipment/VME/Settings/FrontendEnabled":true,"/Equipment/EASIROC/Settings/FrontendEnabled":true,"/Equipment/EASIROC/Variables/RBCPCommunicationOK":true,"/Equipment/EASIROC/Variables/TCPReachable":true,"/Equipment/EASIROC/Variables/TCPConnected":true,"/Equipment/EASIROC/Variables/AcquisitionRunning":true
};
window.DAQ_MOCK_SCENARIOS=Object.freeze({
 running_ok:Object.freeze({...BASE}),
 stopped_warning:Object.freeze({...BASE,"/DAQ/Status/Global/Severity":"WARNING","/DAQ/Status/Global/Summary":"VME frontend disconnected while stopped","/DAQ/Status/Global/CanStart":false,"/DAQ/Status/Global/CanStartReason":"VME frontend disconnected","/DAQ/Status/Run/State":1,"/DAQ/Status/Run/DurationSec":7823,"/DAQ/Status/Frontends/VME/Severity":"WARNING","/DAQ/Status/Frontends/VME/Reason":"VME disconnected while stopped","/DAQ/Status/Frontends/VME/Connected":false,"/DAQ/Status/Runlog/EASIROCEvents":-1,"/Equipment/VME/Statistics/Events per sec.":0,"/Equipment/NIM-EASIROC Physics/Statistics/Events per sec.":0}),
 running_error:Object.freeze({...BASE,"/DAQ/Status/Global/Severity":"ERROR","/DAQ/Status/Global/Summary":"EASIROC frontend disconnected during run","/DAQ/Status/Frontends/EASIROC/Severity":"ERROR","/DAQ/Status/Frontends/EASIROC/Reason":"EASIROC disconnected while running","/DAQ/Status/Frontends/EASIROC/Connected":false,"/Equipment/EASIROC/Variables/RBCPCommunicationOK":false,"/Equipment/EASIROC/Variables/TCPReachable":false,"/Equipment/EASIROC/Variables/TCPConnected":false,"/Equipment/EASIROC/Variables/AcquisitionRunning":false})
});
window.DAQ_MOCK_MESSAGES=Object.freeze(["13:55:23.812 2026/09/21 [mhttpd,INFO] Operator opened Custom DAQ GUI","13:55:18.803 2026/09/21 [feeasiroc,ERROR] TCP stream disconnected","13:54:58.102 2026/09/21 [daq_monitor,WARNING] Disk free space is below warning threshold","13:54:31.030 2026/09/21 [mhttpd,INFO] Run #42 started"]);
