"use strict";
// Sample values for daq.html?mock=1 (RUNNING) and ?mock=stopped (last-run labels).
const RUNNING = {
  "/DAQ/Status/Global/Severity":"WARNING","/DAQ/Status/Global/Summary":"Logger disconnected","/DAQ/Status/Global/CanStart":true,"/DAQ/Status/Global/CanStartReason":"","/DAQ/Status/Run/RunNumber":42,"/DAQ/Status/Run/State":3,"/DAQ/Status/Run/DurationSec":1934,
  "/DAQ/Status/Frontends/VME/Severity":"OK","/DAQ/Status/Frontends/VME/Reason":"VME OK","/DAQ/Status/Frontends/VME/Connected":true,"/DAQ/Status/Frontends/VME/EventSlipCount":0,"/DAQ/Status/Frontends/EASIROC/Severity":"WARNING","/DAQ/Status/Frontends/EASIROC/Reason":"EASIROC disconnected while running","/DAQ/Status/Frontends/EASIROC/Connected":false,"/DAQ/Status/Logger/Severity":"WARNING","/DAQ/Status/Logger/Connected":false,"/DAQ/Status/Logger/CurrentFilename":"/data/run00042.mid","/DAQ/Status/Disk/Severity":"OK","/DAQ/Status/Disk/Path":"/data","/DAQ/Status/Disk/FreeGB":238.6,"/DAQ/Status/Disk/TotalGB":407.5,
  "/Equipment/VME/Statistics/Events per sec.":1248.2,"/Equipment/VME/Statistics/kBytes per sec.":318.7,"/Equipment/VME/Statistics/Events sent":2415890,"/Equipment/NIM-EASIROC Physics/Statistics/Events per sec.":1247.9,"/Equipment/NIM-EASIROC Physics/Statistics/kBytes per sec.":92.4,"/Equipment/NIM-EASIROC Physics/Statistics/Events sent":2415321,
  "/Equipment/VME/Info/V792/BaseAddress":6291456,"/Equipment/VME/Variables/V792/EnabledForRun":true,"/Equipment/VME/Variables/V792/CommunicationOK":true,"/Equipment/VME/Variables/V792/EventCounter":2415890,"/Equipment/VME/Info/V1190/BaseAddress":12648448,"/Equipment/VME/Variables/V1190/EnabledForRun":true,"/Equipment/VME/Variables/V1190/CommunicationOK":true,"/Equipment/VME/Variables/V1190/EventCounter":2415890,"/Equipment/VME/Info/V1720E/BaseAddress":286326784,"/Equipment/VME/Variables/V1720E/EnabledForRun":true,"/Equipment/VME/Variables/V1720E/CommunicationOK":true,"/Equipment/VME/Variables/V1720E/EventCounter":2415890,"/Equipment/VME/Info/V775/BaseAddress":0,"/Equipment/VME/Variables/V775/EnabledForRun":false,"/Equipment/VME/Variables/V775/CommunicationOK":false,"/Equipment/VME/Variables/V775/EventCounter":0,"/Equipment/VME/Info/RPV130/BaseAddress":36848,"/Equipment/VME/Variables/RPV130/EnabledForRun":true,"/Equipment/VME/Variables/RPV130/CommunicationOK":true,"/Equipment/EASIROC/Settings/Network/IPAddress":"192.168.10.26","/Equipment/EASIROC/Variables/EnabledForRun":true,"/Equipment/EASIROC/Variables/TCPConnected":false,"/Equipment/EASIROC/Variables/EventCounter":2415321
};
RUNNING["/Equipment/EASIROC/Variables/RBCPCommunicationOK"] = true;
RUNNING["/Equipment/EASIROC/Variables/TCPReachable"] = true;
RUNNING["/Equipment/EASIROC/Variables/TCPConnected"] = true;
RUNNING["/Equipment/EASIROC/Variables/AcquisitionRunning"] = true;
RUNNING["/DAQ/Status/Frontends/VME/CounterDiscontinuityCount"] = 0;
window.DAQ_MOCK_DATA=Object.freeze(RUNNING);
window.DAQ_MOCK_STOPPED_DATA=Object.freeze({...RUNNING,"/DAQ/Status/Global/Severity":"OK","/DAQ/Status/Global/Summary":"DAQ OK","/DAQ/Status/Global/CanStart":false,"/DAQ/Status/Global/CanStartReason":"EASIROC frontend disconnected","/DAQ/Status/Run/State":1,"/DAQ/Status/Run/DurationSec":0,"/DAQ/Status/Frontends/EASIROC/Reason":"EASIROC disconnected while stopped","/Equipment/VME/Statistics/Events per sec.":0,"/Equipment/NIM-EASIROC Physics/Statistics/Events per sec.":0});
